# Generated by Django 5.0.6 on 2024-07-06 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendMoney',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transaction.transaction')),
                ('send_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_sender', to='user_auth.userbankaccount')),
            ],
            bases=('transaction.transaction',),
        ),
    ]
